### ISSUE TITLE
Refresh tokens support

### ISSUE THREAD

**Issue by massongit** [Jesus/dropbox_api#81]
https://dropbox.tech/developers/migrating-app-permissions-and-access-tokens

The dropbox api supports refresh tokens.
Therefore, I'd like you to support it in this library.

**Comment by tomekdrazek** [comment]
Hi, I added the simplest I think implementation of the refresh tokens. I checked them out against new project with short lived tokens and seems to work fine. The only downside is you must create your own implementation of `DropboxAPI::Token` in order to provide token serialisation routines. The README.md has details how to make a new handshake to generate offline tokens with refresh ability. Any feedback welcome.

**Comment by massongit** [comment]
PR: https://github.com/Jesus/dropbox_api/pull/83

**Comment by Jesus** [comment]
Done in #88

**Comment by massongit** [comment]
We will take some time from the release of the new `dropbox_api` version to the the reflection on our system.
Therefore, if something similar happens in the future, we want you to release the new version as soon as possible.

**Comment by Jesus** [comment]
This is an open source project, if something like this occurs in the future you're welcome to contribute in advance.

**Comment by massongit** [comment]
We can create a PR. In fact, in this case, tomekdrazek created #83 on July 13th, __two months before__ the deadline.
However, only you can merge and release the PR, so we need your help so that we can handle it in a timely manner.
